# YOUR NAME OR TITLE OF YOUR SITE
name: krankofficial

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Harsh Trivedi. I'm a passionate Tech Lover from Kanpur, apart from that I'm a Graphic Designer and an OpenSource enthusiast Inspired by Imagination.

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/harsh98trivedi.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:
  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

  # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: harsh98trivedi
    Color: "#3b5998"
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: harsh98trivedi
    Color: "#DD2A7B"
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: harsh98trivedi
    Color: "#1DA1F2"
    Icon-Class:
      fab fa-twitter

      # THREADS.NET
  - Name: Threads
    URL: https://threads.net/
    Username: harsh98trivedi
    Color: "#000000"
    Icon-Class: fa-solid fa-at
    Text_Color: "#ffffff"

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCS3zvA_2r1iGT7MB3NVCGAw
    Color: "#ff0000"
    Icon-Class: fab fa-youtube

    # EMAIL
  - Name: Email
    URL: "mailto:harshtrivedi@duck.com"
    Icon-Class: fas fa-envelope
    Color: "#e17055"
    Text_Color: "#ffffff"

    # VIMEO
  - Name: Vimeo
    URL: "https://vimeo.com"
    Username: harshtrivedi
    Icon-Class: fab fa-vimeo-v
    Color: "#1ab7ea"
    Text_Color: "#ffffff"

    # MESSENGER
  - Name: Messenger
    URL: https://m.me
    Username: theharshtrivedi
    Color: "#006AFF"
    Icon-Class: fab fa-facebook-messenger

    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id
    Username: "harshtrivedi"
    Color: "#66c0f4"
    Text_Color: "#000000"
    Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username:
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'
  # PINTEREST
  # - Name: Pinterest
  #   URL: https://pinterest.com
  #   Username: 'harsh98trivedi'
  #   Color: '#E60023'
  #   Icon-Class: fab fa-pinterest
  # BEHANCE
  # - Name: Behance
  #   URL: https://www.behance.net
  #   Username: harsh98trivedi
  #   Color: '#1769ff'
  #   Icon-Class: fab fa-behance
  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username:
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble
  # DEVIANTART
  - Name: DeviantArt
    URL: https://www.deviantart.com
    Username: harshtrivedi
    Icon-Class: fab fa-deviantart
    Color: "#05CC46"
    Text_Color: "#ffffff"

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: 314ihryk3edvtusti6il3oy3x5da
    Color: "#1DB954"
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: https://www.soundcloud.com
    Username: harsh98trivedi
    Color: "#FE5000"
    Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username:
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

  # CUSTOM LINK
  - Name: Blog
    URL: https://harsh98trivedi.github.io/blog
    Icon-Class: fas fa-link
    Color: "#ffb142"
    Text_Color: "#ffffff"

  - Name: Links
    URL: https://github.com/harsh98trivedi/links
    Icon-Class: fas fa-link
    Color: "#d94869"
    Text_Color: "#ffffff"

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: "No"

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
